export type Challenge = {
  id: number;
  word: string;
  tip: string;
};

export const WORDS: Challenge[] = [
  { id: 1, word: "Futebol", tip: "Esporte mais popular do Brasil" },
  { id: 2, word: "Gol", tip: "Objetivo principal do jogo" },
  { id: 3, word: "Zagueiro", tip: "Jogador de defesa" },
  { id: 4, word: "Atacante", tip: "Responsável por marcar gols" },
  { id: 5, word: "Meio-campo", tip: "Organiza o jogo" },
  { id: 6, word: "Escanteio", tip: "Cobrança lateral do campo" },
  { id: 7, word: "Falta", tip: "Infração durante o jogo" },
  { id: 8, word: "Pênalti", tip: "Cobrança direta contra o goleiro" },
  { id: 9, word: "Cartão Amarelo", tip: "Advertência ao jogador" },
  { id: 10, word: "Cartão Vermelho", tip: "Expulsão do jogador" },
  { id: 11, word: "Torcida", tip: "Fãs do time" },
  { id: 12, word: "Campeonato", tip: "Competição esportiva" },
  { id: 13, word: "Brasileirão", tip: "Principal liga do Brasil" },
  { id: 14, word: "Libertadores", tip: "Torneio continental sul-americano" },
  { id: 15, word: "Chute", tip: "Ação de bater na bola" },
  { id: 16, word: "Drible", tip: "Finta para enganar o adversário" },
  { id: 17, word: "Goleiro", tip: "Defende o gol" },
  { id: 18, word: "Técnico", tip: "Comandante da equipe" },
  { id: 19, word: "Lateral", tip: "Reposição de bola com as mãos" },
  { id: 20, word: "Bola", tip: "Objeto principal do jogo" },
  { id: 21, word: "Tropa de Elite", tip: "Filme policial brasileiro" },
  { id: 22, word: "Cidade de Deus", tip: "Drama sobre a vida na favela" },
  { id: 23, word: "Central do Brasil", tip: "Drama emocionante brasileiro" },
  { id: 24, word: "Minha Mãe é uma Peça", tip: "Comédia com Paulo Gustavo" },
  { id: 25, word: "A Culpa é das Estrelas", tip: "Drama romântico popular" },
  { id: 26, word: "Vingadores", tip: "Filme de super-heróis famoso" },
  { id: 27, word: "Homem-Aranha", tip: "Franquia adorada no Brasil" },
  { id: 28, word: "Batman: O Cavaleiro das Trevas", tip: "Sucesso de crítica" },
  { id: 29, word: "Titanic", tip: "Clássico de romance e tragédia" },
  { id: 30, word: "Avatar", tip: "Maior bilheteria do cinema" },
  { id: 31, word: "Harry Potter", tip: "Saga de fantasia famosa" },
  { id: 32, word: "O Auto da Compadecida", tip: "Clássico brasileiro" },
  { id: 33, word: "Interestelar", tip: "Ficção científica sobre espaço" },
  { id: 34, word: "Jurassic Park", tip: "Dinossauros e aventura" },
  { id: 35, word: "Matrix", tip: "Filme de ação futurista" },
  { id: 36, word: "Pantera Negra", tip: "Filme de super-herói aclamado" },
  { id: 37, word: "Frozen", tip: "Animação musical famosa" },
  { id: 38, word: "Shrek", tip: "Animação de comédia" },
  { id: 39, word: "Procurando Nemo", tip: "Animação sobre um peixe perdido" },
  { id: 40, word: "Rocky", tip: "Filme clássico de boxe" },
  { id: 41, word: "Café", tip: "Bebida popular para começar o dia" },
  { id: 42, word: "Trabalho", tip: "Atividade diária de muitos" },
  { id: 43, word: "Estudo", tip: "Processo de aprendizado" },
  { id: 44, word: "Mercado", tip: "Lugar para comprar alimentos" },
  { id: 45, word: "Cozinhar", tip: "Preparar alimentos" },
  { id: 46, word: "Limpeza", tip: "Manter a casa organizada" },
  { id: 47, word: "Celular", tip: "Ferramenta essencial do dia a dia" },
  { id: 48, word: "Internet", tip: "Conexão com o mundo" },
  { id: 49, word: "Mensagens", tip: "Formas de comunicação rápida" },
  { id: 50, word: "Transporte", tip: "Meios de locomoção" },
  { id: 51, word: "Ônibus", tip: "Transporte público comum" },
  { id: 52, word: "Carro", tip: "Veículo pessoal" },
  { id: 53, word: "Banho", tip: "Higiene diária" },
  { id: 54, word: "Sono", tip: "Descanso necessário" },
  { id: 55, word: "Acordar", tip: "Início do dia" },
  { id: 56, word: "Comida", tip: "Alimentação diária" },
  { id: 57, word: "Água", tip: "Essencial para a vida" },
  { id: 58, word: "Roupa", tip: "Vestuário usado diariamente" },
  { id: 59, word: "Calçado", tip: "Proteção para os pés" },
  { id: 60, word: "Chave", tip: "Usada para abrir portas" },
  { id: 61, word: "Bicicleta", tip: "Meio de transporte ecológico" },
  { id: 62, word: "Academia", tip: "Lugar para exercícios" },
  { id: 63, word: "Caminhada", tip: "Exercício simples e diário" },
  { id: 64, word: "Trânsito", tip: "Movimentação de veículos" },
  { id: 65, word: "Relógio", tip: "Serve para ver as horas" },
  { id: 66, word: "Agenda", tip: "Organizar compromissos" },
  { id: 67, word: "Travesseiro", tip: "Usado para dormir melhor" },
  { id: 68, word: "Escova de dentes", tip: "Higiene bucal" },
  { id: 69, word: "Sabonete", tip: "Limpeza do corpo" },
  { id: 70, word: "Shampoo", tip: "Higiene dos cabelos" },
  { id: 71, word: "Computador", tip: "Ferramenta para trabalho e estudo" },
  { id: 72, word: "Teclado", tip: "Usado para digitar" },
  { id: 73, word: "Mouse", tip: "Controle do computador" },
  { id: 74, word: "Televisão", tip: "Entretenimento doméstico" },
  { id: 75, word: "Sofá", tip: "Móvel para descanso" },
  { id: 76, word: "Mesa", tip: "Móvel para refeições e trabalho" },
  { id: 77, word: "Cama", tip: "Lugar para dormir" },
  { id: 78, word: "Porta", tip: "Entrada de ambientes" },
  { id: 79, word: "Janela", tip: "Entrada de luz e ventilação" },
  { id: 80, word: "Ventilador", tip: "Aparelho para refrescar" },
  { id: 81, word: "Ar-condicionado", tip: "Climatiza o ambiente" },
  { id: 82, word: "Lâmpada", tip: "Fonte de luz artificial" },
  { id: 83, word: "Fogão", tip: "Usado para cozinhar" },
  { id: 84, word: "Geladeira", tip: "Mantém alimentos frescos" },
  { id: 85, word: "Copo", tip: "Usado para bebidas" },
  { id: 86, word: "Panela", tip: "Cozinhar alimentos" },
  { id: 87, word: "Rádio", tip: "Transmite músicas e notícias" },
  { id: 88, word: "Chuveiro", tip: "Banho diário" },
  { id: 89, word: "Trabalho Remoto", tip: "Atividade profissional em casa" },
  { id: 90, word: "Reunião", tip: "Encontro para decisões" },
  { id: 91, word: "Entrega", tip: "Serviços de delivery" },
  { id: 92, word: "Aplicativo", tip: "Programas do celular" },
  { id: 93, word: "Pix", tip: "Pagamento instantâneo" },
  { id: 94, word: "Banco", tip: "Serviços financeiros" },
  { id: 95, word: "Conta", tip: "Fatura mensal" },
  { id: 96, word: "Salário", tip: "Pagamento pelo trabalho" },
  { id: 97, word: "Passeio", tip: "Atividade de lazer" },
  { id: 98, word: "Família", tip: "Convivo diário importante" },
  { id: 99, word: "Amigos", tip: "Companhia social" },
  { id: 100, word: "Casa", tip: "Lar para viver" },
];
